In [243]:
# Reference for exercises
import numpy as np
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

In [244]:
# How many negative numbers are there?

mask = a < 0
mask

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [247]:
# there are four negative numbers
a[mask]

array([-2, -1, -6, -7])

In [248]:
len(a[mask])

4

In [250]:
# How many positive numbers are there?
mask = a > 0
mask

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True, False])

In [251]:
# there are 5 positive numbers
a[mask]

array([ 4, 10, 12, 23,  3])

In [252]:
len(a[mask])

5

In [253]:
# How many even positive numbers are there?

mask = (a % 2 == 0) & (a > 0)
mask

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False])

In [254]:
# there are three even, positive numbers
a[mask]

array([ 4, 10, 12])

In [255]:
len(a[mask])

3

In [ ]:
# If you were to add 3 to each data point, how many positive numbers would there be?

new_list = []

for x in a:
    new_list.append(x + 3)
new_list

# Review
# b = a + 3
# b [ b > 0 ]

In [ ]:
new_array = np.array(new_list)

In [ ]:
mask = (new_array > 0)
mask

In [ ]:
# there would be 10 positive numbers

len(new_array[mask])

In [261]:
# If you squared each number, what would the new mean and standard deviation be?
## Review
## (a ** 2).mean()
## (a ** 2).std
array = np.array(a)

In [262]:
(array ** 2).mean()

74.0

In [259]:
(a ** 2).mean()

74.0

In [260]:
(a ** 2).std()

144.0243035046516

In [264]:
# # A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. 
# Center the data set.
import numpy as np
import scipy.stats as stats

mean = a.mean()
mean

3.0

In [263]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [265]:
new_list = []

for x in a:
    new_list.append(x - 3)

new_array = np.array(new_list)
new_array.mean()

0.0

In [ ]:
Calculate the z-score for each data point
z = (X – μ) / σ
X is a single raw data value
μ is the population mean
σ is the population standard deviation

In [6]:
mean = a.mean()

In [7]:
std = a.std()

In [9]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [ ]:
# a - mean / std

In [268]:
## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:

In [23]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum 
# of all the numbers in above list
import numpy as np
array = np.array(a)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
type(array)

numpy.ndarray

In [269]:
sum(a)

55

In [27]:
sum_of_a = array.sum()
sum_of_a

55

In [28]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of 
# all the numbers in the above list

min_of_a = array.min()
min_of_a

1

In [270]:
max(a)

10

In [31]:
# Exercise 3 - Make a variable named max_of_a to hold the max 
# number of all the numbers in the above list

max_of_a = array.max()
max_of_a

10

In [32]:
# Exercise 4 - Make a variable named mean_of_a to hold the average 
# of all the numbers in the above list

mean_of_a = array.mean()
mean_of_a

5.5

In [34]:
# Exercise 5 - Make a variable named product_of_a to hold the product 
# of multiplying all the numbers in the above list together

product_of_a = array.prod()
product_of_a

3628800

In [44]:
# Exercise 6 - Make a variable named squares_of_a. 
# It should hold each number in a squared like [1, 4, 9, 16, 25...]

# Long way below
# new_list = []

# for x in a:
#     new_list.append(x ** 2)
# new_list

# squares_of_a = np.array(new_list)
# squares_of_a

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [48]:
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [54]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

array = np.array(a)

In [59]:
mask = (array % 2 != 0)
mask

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [62]:
odds_in_a = array[mask]
odds_in_a

array([1, 3, 5, 7, 9])

In [63]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

array = np.array(a)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
mask = (array % 2 == 0)
mask

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [66]:
evens_in_a = array[mask]
evens_in_a

array([ 2,  4,  6,  8, 10])

In [67]:
## What about life in two dimensions? 
## A list of lists is matrix, a table, a spreadsheet, a chessboard...

## Setup 2: Consider what it would take to find the 
# sum, 
# min, 
# max, 
# average, 
# sum, 
# product, 
# and list of squares for this list of two lists.

b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [70]:
b_array = np.array(b)
b_array

array([[3, 4, 5],
       [6, 7, 8]])

In [78]:
b_array.sum(), b_array.min(), b_array.max()

(33, 3, 8)

In [82]:
np.average(b), b_array.sum(), b_array.prod()

(5.5, 33, 20160)

In [93]:
type(b)
print(b)
type(b_array)

[[3, 4, 5], [6, 7, 8]]


numpy.ndarray

In [94]:
new_list = []

for x in list(b_array):
    new_list.extend(x)

new_list

[3, 4, 5, 6, 7, 8]

In [100]:
new_array = np.array(new_list)
new_array

array([3, 4, 5, 6, 7, 8])

In [102]:
square_list = []
for x in new_array:
    square_list.append(x ** 2)
square_list

[9, 16, 25, 36, 49, 64]

In [105]:
# Exercise 1 - refactor the following to use numpy. 
# Use sum_of_b as the variable. 
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)


In [107]:
b

[[3, 4, 5], [6, 7, 8]]

In [109]:
b_array = np.array(b)
b_array

array([[3, 4, 5],
       [6, 7, 8]])

In [113]:
sum_of_b = 0
for row in b_array:
    sum_of_b += sum(row)
    
print(sum_of_b)

33


In [130]:
b_array.sum()

33

In [120]:
 b_array

array([[3, 4, 5],
       [6, 7, 8]])

In [124]:
b

[[3, 4, 5], [6, 7, 8]]

In [127]:
# Exercise 2 - refactor the following to use numpy.
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

b_array.min()

3

In [128]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
b_array.max()

8

In [129]:
# Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
b_array.mean()

5.5

In [ ]:
# Exercise 5 - refactor the following to use numpy for calculating the 
# product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number


In [131]:
b_array.prod()

20160

In [133]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b_array:
    for number in row:
        squares_of_b.append(number**2)

In [134]:
b

[[3, 4, 5], [6, 7, 8]]

In [135]:
b_array

array([[3, 4, 5],
       [6, 7, 8]])

In [136]:
list(b_array)

[array([3, 4, 5]), array([6, 7, 8])]

In [137]:
np.square(b)

array([[ 9, 16, 25],
       [36, 49, 64]])

In [ ]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [140]:
mask = (b_array % 2 != 0)
mask

array([[ True, False,  True],
       [False,  True, False]])

In [142]:
odds_in_b = b_array[mask]
odds_in_b

array([3, 5, 7])

In [ ]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [143]:
mask = (b_array % 2 == 0)
mask

array([[False,  True, False],
       [ True, False,  True]])

In [144]:
b_array[mask]

array([4, 6, 8])

In [145]:
# Exercise 9 - print out the shape of the array b.
b_array.shape

(2, 3)

In [146]:
# Exercise 10 - transpose the array b.
b_array.transpose()

array([[3, 6],
       [4, 7],
       [5, 8]])

In [152]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
single_list = []
for x in b_array:
    single_list.extend(x)
    
single_list

[3, 4, 5, 6, 7, 8]

In [153]:
# Exercise 12 - reshape the array b to be a list of 6 lists, 
# each containing only 1 number (6 x 1)

b_array.shape

(2, 3)

In [154]:
b_array.reshape(6, 1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [271]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable 
# is a numpy array prior to using numpy array methods.

In [159]:
# Exercise 1 - Find the min, max, sum, and product of c.
c
c_array = np.array(c)
c_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [164]:
c_array.min(), c_array.max(), c_array.sum(), c_array.prod()

(1, 9, 45, 362880)

In [165]:
# Exercise 2 - Determine the standard deviation of c.

c_array.std()

2.581988897471611

In [166]:
# Exercise 3 - Determine the variance of c.

c_array.var()

6.666666666666667

In [168]:
# Exercise 4 - Print out the shape of the array c

c_array.shape

(3, 3)

In [178]:
# Exercise 5 - Transpose c and print out transposed result.

print(c_array.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [180]:
# Exercise 6 - Get the dot product of the array c with c. 

np.dot(c_array, c_array)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [211]:
# Exercise 7 - Write the code necessary to sum up the 
# result of c times c transposed. Answer should be 261.

in_arr1 = c_array
in_arr2 = c_array
   
print ("1st Input array : ", in_arr1)
print ("2nd Input array : ", in_arr2)

out_arr = np.multiply(in_arr1, in_arr2) 
print ("Resultant output array: ", out_arr)

out_arr

1st Input array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd Input array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Resultant output array:  [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [272]:
## review 
(c.T *c).sum()

AttributeError: 'list' object has no attribute 'T'

In [273]:
type(c)

list

In [207]:
array = out_arr.transpose()
array.sum()

285

In [209]:
# Exercise 8 - Write the code necessary to determine the 
# product of c times c transposed. Answer should be 131681894400.

in_arr1 = c_array
in_arr2 = c_array
   
print ("1st Input array : ", in_arr1)
print ("2nd Input array : ", in_arr2)

out_arr = np.multiply(in_arr1, in_arr2) 
print ("Resultant output array: ", out_arr)

1st Input array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
2nd Input array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Resultant output array:  [[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [213]:
array = out_arr.transpose()
array.prod()

131681894400

In [214]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [217]:
# Exercise 1 - Find the sine of all the numbers in d

d_array = np.array(d)
d_array

array([[ 90,  30,  45,   0, 120, 180],
       [ 45, -90, -30, 270,  90,   0],
       [ 60,  45, -45,  90, -45, 180]])

In [220]:
np.sin(d_array)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [223]:
# Exercise 2 - Find the cosine of all the numbers in d

np.cos(d_array)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [224]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d_array)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [227]:
# Exercise 4 - Find all the negative numbers in d

mask = (d_array < 0)
mask

array([[False, False, False, False, False, False],
       [False,  True,  True, False, False, False],
       [False, False,  True, False,  True, False]])

In [228]:
d_array[mask]

array([-90, -30, -45, -45])

In [229]:
# Exercise 5 - Find all the positive numbers in d

mask = (d_array > 0)
mask

array([[ True,  True,  True, False,  True,  True],
       [ True, False, False,  True,  True, False],
       [ True,  True, False,  True, False,  True]])

In [230]:
d_array[mask]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [232]:
# Exercise 6 - Return an array of only the unique numbers in d

np.unique(d_array)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [235]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d_array))

11

In [236]:
# Exercise 8 - Print out the shape of d.

d_array.shape

(3, 6)

In [239]:
# Exercise 9 - Transpose and then print out the shape of d.

d_array.transpose().shape

(6, 3)

In [240]:
# Exercise 10 - Reshape d into an array of 9 x 2

d_array.reshape(9, 2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])